### ISSUE TITLE
Incorrect STASH code for soil respiration

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-esm1.5-configs#14]
Though this isn't strictly related to `amami` post-processing, the soil respiration might be incorrectly encoded in the ACCESS_Archiver tool

https://forum.access-hive.org.au/t/carbon-cycle-evaluation-access-and-cable-pop/1729/4

Is this a problem for the proposed post-processing (#3)?

**Comment by MartinDix** [comment]
See https://github.com/ACCESS-NRI/um2nc-standalone/issues/25
