### ISSUE TITLE
Configuration naming scheme

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/access-esm1.5-configs#19]
Anyone with opinions about what the names of the initial configurations should be please chime in here. The CMS repo just called them `historical`, `pre-industrial`, `miocene` etc. 

The OM2 configurations, by necessity, have resolution, forcing product and forcing mode in the name, e.g. `release-1deg_jra55_iaf`.

Do we want to adopt any naming convention like this? Clearly a forcing product and mode is not required, but perhaps it useful to include a resolution as a standard part of our configuration naming for consistency and transparency, to make it obvious to users what this refers to. This may also be informed by/be consistent with the input file naming scheme.

So we could start with:

`1deg_n96_hist_conc`
`1deg_n96_pi_conc`

given that emissions driven will be near-term targets they would be something like

`1deg_n96_hist_emiss`
`1deg_n96_pi_emiss`

Those are fairly terse, could go for longer and more descriptive `historical` and `pre-industrial`.

Thoughts?

**Comment by CodeGat** [comment]
Linking https://github.com/ACCESS-NRI/access-esm1.5-configs/pull/18 (specifically https://github.com/ACCESS-NRI/access-esm1.5-configs/pull/18/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R10) as this is relevant to the documentation in that PR.

**Comment by aidanheerdegen** [comment]
> as this is relevant to the documentation in that PR.

Can you guess what I was reviewing when I decided to post this?

**Comment by CodeGat** [comment]
I don't necessarily have any expertise in this bit, but for whatever is decided we should still prepend `[dev|release]-<config>` for whatever `<config>`. 

`Xdeg` would be good to keep if it's common between all/most models. 

What is meant by `n96`? 

If we go with long names, can we make `-` reserved, as well as `_`? We currently use `-` as a separator for `[dev|release]-<config>-<tag>`.

**Comment by aidanheerdegen** [comment]
`n96` is the atmosphere "resolution" (it's a spectral model so this doesn't really have a well defined spatial resolution I believe but @blimlim is better placed to comment).

I agree `-` should be reserved, so `pre_historical` is we want to "go long or go home".

**Comment by CodeGat** [comment]
Even with `pre_historical`, we've been using `_` as a separator between 'fields', for lack of a better word. Like `1deg_jra55_iaf_bgc`, `_` separates resolution, forcing product and forcing mode (and the BGC bit). I think we're running out of freely usable separators :D

**Comment by aidanheerdegen** [comment]
> Even with `pre_historical`, we've been using `_` as a separator between 'fields'

So `prehistorical` it is! :)

**Comment by blimlim** [comment]
> `n96` is the atmosphere "resolution" (it's a spectral model so this doesn't really have a well defined spatial resolution I believe

From what I understand, the UM uses a finite difference scheme with regular lat/lon grid. The `n96` grid has a lat x lon grid cell size of 1.25 x 1.875 degrees, which results in there being 145 latitudes and 192 longitudes. I'm not sure how it originated, but the `nXY` naming scheme seems to just halve the number of longitudes, e.g. `n48` has 96 longitudes, and I think `n216` has 432.

Not sure if I have any ideas that are too useful here! We could go with the CMIP6 experiment names, e.g. `piControl` and `historical` from the [experiment list here](https://wcrp-cmip.org/cmip-model-and-experiment-documentation/#experiments) (scroll down to the CMIP `activity ID` to see the relevant ones), though that might cause problems down the line. E.g. many do use dashes in their name, and the emissions driven experiments are named things like `esm-piControl` (I'd probably get confused thinking this was referring to the model rather than the experiment). If a configuration is from a CMIP experiment though, it would probably be good state which one it is somewhere in the configuration (maybe in the readme?).


> This may also be informed by/be consistent with the input file naming scheme.

If we copy the naming schemes we've been [thinking about for the input files](https://github.com/ACCESS-NRI/access-esm1.5-configs/issues/2#issuecomment-2175502845) , do you think it reads ok or is it a bit unwieldy? E.g.  `release-global.oi_1deg.a_N96_historical_conc`

**Comment by aidanheerdegen** [comment]
> From what I understand, the UM uses a finite difference scheme with regular lat/lon grid. The `n96` grid has a lat x lon grid cell size of 1.25 x 1.875 degrees, which results in there being 145 latitudes and 192 longitudes. I'm not sure how it originated, but the `nXY` naming scheme seems to just halve the number of longitudes, e.g. `n48` has 96 longitudes, and I think `n216` has 432.

Sorry for the wrong information and thanks for the correction @blimlim! 
 
> Not sure if I have any ideas that are too useful here! We could go with the CMIP6 experiment names, e.g. `piControl` and `historical` from the [experiment list here](https://wcrp-cmip.org/cmip-model-and-experiment-documentation/#experiments) (scroll down to the CMIP `activity ID` to see the relevant ones), though that might cause problems down the line. E.g. many do use dashes in their name, and the emissions driven experiments are named things like `esm-piControl` (I'd probably get confused thinking this was referring to the model rather than the experiment). If a configuration is from a CMIP experiment though, it would probably be good state which one it is somewhere in the configuration (maybe in the readme?).

We've chosen to define an experiment as a "realisation of a configuration". What we call an experiment CMIP calls a simulation. A CMIP experiment is a description of a protocol for a simulation.

That is a long-winded way of saying in our way of working `piControl` should be the name of the branch (experiment) that is a specific realisation (series of runs) of a pre-industrial configuration.

> > This may also be informed by/be consistent with the input file naming scheme.
> 
> If we copy the naming schemes we've been [thinking about for the input files](https://github.com/ACCESS-NRI/access-esm1.5-configs/issues/2#issuecomment-2175502845) , do you think it reads ok or is it a bit unwieldy? E.g. `release-global.oi_1deg.a_N96_historical_conc`

Yes I think that is probably unwieldy. Because we get to define what a name means I think we can say that it is, for example:

`<spatial_extent>_<ocean_resolution>_<atmosphere_resolution>_<scenario>+<modifier>`

and assume the `oi` and `a` bits. I think they tend to make it more difficult to comprehend.

If we break it up into those fields it might help

| Field | Possible values | 
|--------|--------|
| Spatial extent | `global`,`pan-antarctic`,`regional`,`aust` | 
| Ocean resolution | `1deg`,  `2deg`, `025deg` |
| Atmosphere resolution | `n48`, `n96`, `n512` | 
| Scenario | `historical`, `preindustrial`, `pliocene`, `lgm`, `ssp585` | 
| Modifiers | `emiss`, `conc`|

Is "scenario" a good description? It could be more specific, e.g. "chronological period", if that was all that it is ever required for, but as I included a CMIP future scenario if we agree that is the appropriate then scenario is probably a better term. 

I added "Modifiers" as a general bucker for some extra specification, and there could be multiple but I can't think of any.

Any opinions @MartinDix?

**Comment by MartinDix** [comment]
scenario is better than chronological period because some cases don't have a real date range associated with them, e.g. 4xCO2. There are more possible modifiers, e.g. land use only, GHG only. Not sure that conc/emiss is the best choice. We should check with Tilo and Tammas.

**Comment by dougiesquire** [comment]
Probably not useful input at this point, but having experiment names that start with a number can be a little annoying sometimes because many languages do not allow variable names that start with a number. I guess we're already pretty much already locked in to these so... just ignore me.

**Comment by MartinDix** [comment]
For ESM1.5/6 we don't need the spatial extent. It might be useful sometime further into the future. To avoid having a number at the start could put the atmosphere first, n96_1deg ...

**Comment by aidanheerdegen** [comment]
> There are more possible modifiers, e.g. land use only, GHG only. Not sure that conc/emiss is the best choice. We should check with Tilo and Tammas.

Who/How do we do this?

I only suggested a `+<modifier>` in case that was a useful idea. Particularly if modifiers are optional, if there was the possibility of multiple modifiers for a given configuration, or if there was a "base" configuration and an equivalent with some modification. If there is always a modifier field then it probably makes sense to use a `_` separator.

> having experiment names that start with a number can be a little annoying sometimes because many languages do not allow variable names that start with a number.

> For ESM1.5/6 we don't need the spatial extent. It might be useful sometime further into the future. To avoid having a number at the start could put the atmosphere first, n96_1deg ...

So proposal for configuration name is:
```
<atmosphere_resolution>_<ocean_resolution>_<scenario>+<modifier>
```
with corresponding branches with `release-` and `dev-` prepended.

**Comment by tammasloughran** [comment]
Should probably be named something like concentration-driven vs. interactive carbon cycle, because the pre-industrial simulation  does not have emissions but can have an interactive carbon cycle enabled. The emissions, whether 0, constant of variable are indicated by the "scenario" descriptor.

**Comment by aidanheerdegen** [comment]
> The emissions, whether 0, constant of variable are indicated by the "scenario" descriptor.

So what should the scenario descriptors be? `historicalconcentrationdriven` and `preindustrialconcentrationdriven`? Or shortened versions, e.g. `histconc` and `piconc`?

Or am I misunderstanding? 

We need some idea of the realistic span of possibilities to make a reasonable decision at this point in time.

**Comment by tammasloughran** [comment]
Maybe we should only abbreviate if there is some character restriction. The word "driven" may not be needed. 

Examples:

`preindustrial-interactiveC`
`preindustrial-concentrations`
`historical-interactiveC`
`historical-emissions`
`historical-emissions-noLUC`
`ssp126-emissions`
`ssp126-concentrations`

We could use camel font to make it easier to read or having some sort of separator between the scenario and configuration modifiers.

It seems there are already some scenario names for CMIP7 but sometimes I don't think they are very clear. So many abbreviations... like, prefixing experiment names with `esm-` is vague and doesn't really indicate how the model should be configured. I'm familiar with the flat10 experiments but I don't think that name would make sense to everyone. Also, I'm not very familiar with AerChemMIP and I have no idea what SLCF is.

![image](https://github.com/ACCESS-NRI/access-esm1.5-configs/assets/9049976/2efca0a5-091d-4619-8230-e3b70fe09ab0)

**Comment by aidanheerdegen** [comment]
Thanks @tammasloughran. 

Yes we're a little constrained on the separators. Your examples are great, and I think they lend themselves well to the idea of a base scenario with modifiers, e.g.
```
preindustrial+interactiveC
preindustrial+concentrations
historical+interactiveC
historical+emissions
historical+emissions+noLUC
ssp126+emissions
ssp126+concentrations
```

In a 2D table with just two mutually exclusive modifiers it looks like:

| Base Scenario | interactiveC | concentrations |
|--------|--------|--------|
| `preindustrial` | `preindustrial+interactiveC` | `preindustrial+concentrations` |
| `historical` | `historical+interactiveC` | `historical+concentrations` |
| `ssp126` | `ssp126+interactiveC` | `ssp126+concentrations` |

Which I've done to illustrate there is semantic value in separating the base scenario from the modifier, because now it is easy to establish relationships between base scenarios that share the same modifiers.

You'd need a third dimension to represent `noLUC`, but it isn't important, the table above was just intended to illustrate the relationships and how they're reflected in a naming scheme.

Have I convinced you yet?

**Comment by aidanheerdegen** [comment]
One last question, can we handle mixed case ok @CodeGat? Specifically examples like `preindustrial+interactiveC` and `historical+emissions+noLUC`?

**Comment by CodeGat** [comment]
Yeah thats fine :+1:

**Comment by aidanheerdegen** [comment]
Ok. Decision time!

We'll go with `preindustrial+concentrations` and `historical+emissions` for our two released configurations.

This means we'll have the following branches:

`release-preindustrial+concentrations`
`release-historical+emissions`

for those two released configs. 

We need to decide if we'll have corresponding `dev-` branches and use the same workflow as we've done with OM2. That needs consultation with the @ACCESS-NRI/ocean team.
