### ISSUE TITLE
Pre-industrial experiment run time

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/access-esm1.5-configs#31]
The `pre-industrial` configuration currently sets the run time to 1 month, which was helpful for testing it. The `historical` configuration will require a 1 year runtime, due to the land use being updated at the end of each year. Checking here whether we'd like to increase the `pre-industrial` default run time to a year just for consistency before the release?

**Comment by penguian** [comment]
Closed by PR #30 merge.
