### ISSUE TITLE
Update cice output variables in pre-industrial and historical configurations

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/access-esm1.5-configs#33]
- [ ] The historical configuration currently saves daily sea ice output for a few variables. This is unlikely to be used, and so should be removed from the default settings.
- [ ] Several sea ice diagnostics are currently impacted by a coupling bug. See [this issue](https://github.com/ACCESS-NRI/cice4/issues/7) and this [forum post](https://forum.access-hive.org.au/t/issue-with-cice-diagnostic-dvidtt-in-access-esm-the-cmip6-pre-industrial-archive/2249) for background. While the bug is still present, any of these variables should be removed from the default output.

**Comment by anton-seaice** [comment]
Why are we turning off daily output? I guess there's some discussion in the ESM working group? (@aidanheerdegen ?)

**Comment by blimlim** [comment]
My understanding is that the daily ice fields for ESM runs usually don't have too much attention paid to them. @MartinDix is this correct?
