### ISSUE TITLE
Set CICE restart frequency to yearly

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/access-esm1.5-configs#48]
Following on from https://github.com/payu-org/payu/issues/471, and to match the output frequency of other model components & run length, we need to set cice to produce annual restarst.

In `cice.nml`:

we need to set ` dumpfreq       = 'y' `

and document somewhere that to change the run length you need to also change this setting?

Questions from me:

Which branches do I make the PR to ?
Which bit of documentation does this go in ?

**Comment by aidanheerdegen** [comment]
> Which branches do I make the PR to ?

The `dev-*` ones

https://github.com/ACCESS-NRI/access-esm1.5-configs/branches/all?query=dev-

> Which bit of documentation does this go in ?

Would be good to have an inline comment in the namelist explaining this needs to be changed if runtime is set to < 1 year.

@atteggiani and @blimlim are working on the Hive docs run a model page, which is where this should also be noted I think.
