### ISSUE TITLE
Add um2netcdf conversion to configurations

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/access-esm1.5-configs#59]
The payu, conda, and um2nc infrastructure is now in place to add automated NetCDF conversion to the ESM1.5 configurations. This will involve adding a `postscript` to the `config.yaml` files, and a PBS job submission script under a `scripts` directory.

**Comment by MartinDix** [comment]
At the moment this is creating files with the original UM file names, e.g. `aiihca.paa1jan.nc`. For use with intake etc it would be better to move to the naming used in the p73 archive, so this would become `aiicha.pa-010101_mon.nc` . pe files would have `pe-010101_dai.nc` suffix.

Also change the NetCDF subdirectory to netCDF

**Comment by MartinDix** [comment]
The original CSIRO scripts renamed the UM files as part of the archiving

```
for fmonth in `ls aiihca.p?*`; do
        sdate=`~access/umdir/vn7.3/normal/cm1scripts/umdate -b64 ${fmonth} | cut --delimiter=" " --fields=8 | cut --delimiter="-" --output-delimiter=\0 --fields=1-3 `
        mv ${fmonth} ${archivedir}/history/atm/${RUNID}.p${fmonth:8:1}-${sdate}
done
```

The umdate script reads the file header
```
~access/umdir/vn7.3/normal/cm1scripts/umdate -b64 aiihca.pa50jan
aiihca.pa50jan:  First 1850-01-01 00:00:00,  Last 1850-01-01 00:00:00,  Interval 2019-04-11 07:40:47
```

Could be better done with mule these days.
