### ISSUE TITLE
Create a pre-industrial control configuration

### ISSUE THREAD

**Issue by penguian** [ACCESS-NRI/access-esm1.5-configs#6]
Create a pre-industrial control configuration based on https://github.com/coecms/access-esm/tree/pre-industrial but using executables created by ACCESS-NRI.

**Comment by penguian** [comment]
@aidanheerdegen Could I please have permissions to assign myself to this issue and create the `pre-industrial` branch?

**Comment by aidanheerdegen** [comment]
Done.
