### ISSUE TITLE
Updates to archived atmospheric variables

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/access-esm1.5-configs#77]
Standard and detailed sets are saving 3,229 `EVAP FROM SOIL SURF -AMOUNT KG/M2/TS`. This is just a scaled version of 3,296 `EVAP FROM SOIL SURF : RATE   KG/M2/S` so is both useless and confusing.

**Comment by MartinDix** [comment]
Use extra variables for daily
3,217
3,234
8,234
8,235

**Comment by aidanheerdegen** [comment]
@blimlim could you add some info about what those variables are, so we have an audit trail of what was added.
