### ISSUE TITLE
Problem with stash diagnostic 1,291 DIRECT COMPONENT OF SURF PAR FLUX

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/access-esm1.5-configs#93]
@har917 and @rml599gh noticed that this variable isn't saved correctly (note that it's not included in the diagnostics saved in released configurations). However 2,290 TOTAL DOWNWARD PAR FLUX AT SURFACE is saved correctly. Here results from Jan of year 101 of PI control.

![fpar](https://github.com/user-attachments/assets/9f2f66f3-84cb-491d-bf38-6ca2cfb29181)

**Comment by rml599gh** [comment]
@MartinDix - thanks for pointing this out. It will likely be useful when I get back to looking at the sensitivity of GPP to the radiation split between NIR and VIS.

**Comment by MartinDix** [comment]
According to the time code in the STASHmaster file these variables are available every time step.
```
1|    1 |    1 |  290 |TOTAL DOWNWARD PAR FLUX AT SURFACE  |
2|    1 |    0 |    1 |    1 |    5 |   -1 |   -1 |    0 |    0 |    0 |    0 |
...
1|    1 |    1 |  291 |DIRECT COMPONENT OF SURF PAR FLUX   |
2|    1 |    0 |    1 |    1 |    5 |   -1 |   -1 |    0 |    0 |    0 |    0 |
```

Time code is line 2 column 3 with meaning 
1 Every timestep.
2 Every long wave radiation timestep.
3 Every short wave radiation timestep.

However printing values showed that the direct component was only valid on radiation time steps. 

Here compare annual means of 1 year runs with 1,291 saved only on radiation steps with a run that does radiation every time step  (35% slower).

![fpar1](https://github.com/user-attachments/assets/6d0d37ff-41da-42a5-88e6-fff6e82eeffb)

This is the ratio of the direct to the total from these runs

![fpar3](https://github.com/user-attachments/assets/2b2e75de-6091-4675-984e-56356a2032db)

Therefore unless this field is required every time step the suggested fix is to modify the STASHmaster_A file to have
```
1|    1 |    1 |  291 |DIRECT COMPONENT OF SURF PAR FLUX   |
2|    1 |    0 |    3 |    1 |    5 |   -1 |   -1 |    0 |    0 |    0 |    0 |
```

This does not otherwise change results.

**Comment by MartinDix** [comment]
STASHmaster_A modified in https://github.com/ACCESS-NRI/model-config-inputs/actions/runs/11624251492

**Comment by MartinDix** [comment]
When adding this change to ESM1.6, noticed that the STASHmaster file was modified incorrectly with a change to the grid code rather than the time code. Anyone who tried to save 1,291 would have got the same weird pattern, but with bonus missing values over land.
